# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-14 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='creator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('password', models.CharField(max_length=15)),
                ('contact', models.IntegerField(blank=True, null=True)),
                ('field', models.CharField(choices=[('py', 'PYTHON DJANGO'), ('J', 'core java'), ('AJ', 'Advance java'), ('Asp', 'visual stdio'), ('cpp', 'oops')], default='python', max_length=12)),
                ('age', models.IntegerField(default=20)),
                ('profile_image', models.ImageField(upload_to='profile')),
            ],
        ),
    ]
