# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 11:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 16, 11, 51, 41, 665874, tzinfo=utc)),
        ),
    ]
