# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 10:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20170316_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 19, 10, 8, 31, 136774, tzinfo=utc)),
        ),
    ]
