# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 10:11
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0003_auto_20170319_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=360)),
                ('created', models.DateTimeField(default=datetime.datetime(2017, 3, 19, 10, 11, 54, 595254, tzinfo=utc))),
                ('pub_date', models.DateTimeField(blank=True, null=True)),
                ('likes', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 19, 10, 11, 54, 592251, tzinfo=utc)),
        ),
    ]
