# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-04 07:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20170404_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 4, 7, 53, 19, 481038, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='creater',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 4, 7, 53, 19, 481038, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 4, 7, 53, 19, 481038, tzinfo=utc)),
        ),
    ]
