# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-06 12:05
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0010_auto_20170404_1323'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(max_length=255)),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2017, 4, 6, 12, 5, 13, 533248, tzinfo=utc))),
                ('likes', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='giveaways',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('giveaway_name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('docfile', models.FileField(upload_to='documents/%y/%m/%d')),
                ('screen_shot1', models.ImageField(upload_to='document/%y/%m/%d')),
                ('screen_shot2', models.ImageField(upload_to='document/%y/%m/%d')),
                ('screen_shot3', models.ImageField(upload_to='document/%y/%m/%d')),
                ('github_link', models.CharField(max_length=256, null=True)),
                ('website_link', models.CharField(max_length=256, null=True)),
                ('likes', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='creater',
            name='author',
        ),
        migrations.RemoveField(
            model_name='creater',
            name='created',
        ),
        migrations.RemoveField(
            model_name='creater',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='creater',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='creater',
            name='age',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='creater',
            name='area_of_intrest',
            field=models.CharField(choices=[('py', 'PYTHON DJANGO'), ('J', 'core java'), ('AJ', 'Advance java'), ('Asp', 'visual stdio'), ('cpp', 'oops')], default='python', max_length=12),
        ),
        migrations.AddField(
            model_name='creater',
            name='contact',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creater',
            name='email',
            field=models.EmailField(default=None, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creater',
            name='password',
            field=models.CharField(default=None, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creater',
            name='profile_image',
            field=models.ImageField(default=None, upload_to='giveaways'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 6, 12, 5, 13, 517619, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='creater',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 6, 12, 5, 13, 517619, tzinfo=utc)),
        ),
    ]
