# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-07 14:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_auto_20170406_1735'),
    ]

    operations = [
        migrations.CreateModel(
            name='creator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=15)),
                ('contact', models.IntegerField(blank=True, null=True)),
                ('area_of_intrest', models.CharField(choices=[('py', 'PYTHON DJANGO'), ('J', 'core java'), ('AJ', 'Advance java'), ('Asp', 'visual stdio'), ('cpp', 'oops')], default='python', max_length=12)),
                ('age', models.IntegerField(default=20)),
                ('profile_image', models.ImageField(upload_to='/media')),
            ],
        ),
        migrations.DeleteModel(
            name='creater',
        ),
        migrations.AlterField(
            model_name='comment',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 7, 14, 32, 32, 516298, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 7, 14, 32, 32, 531925, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 7, 14, 32, 32, 516298, tzinfo=utc)),
        ),
    ]
