# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-07 15:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_auto_20170407_2016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creator',
            name='area_of_intrest',
        ),
        migrations.AddField(
            model_name='creator',
            name='field',
            field=models.CharField(choices=[('py', 'PYTHON DJANGO'), ('J', 'core java'), ('AJ', 'Advance java'), ('Asp', 'visual stdio'), ('cpp', 'oops')], default='python', max_length=12),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 7, 15, 10, 22, 560833, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='creator',
            name='profile_image',
            field=models.ImageField(upload_to='/documents'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 7, 15, 10, 22, 560833, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 7, 15, 10, 22, 545210, tzinfo=utc)),
        ),
    ]
