# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-08 07:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_auto_20170407_2049'),
    ]

    operations = [
        migrations.DeleteModel(
            name='giveaways',
        ),
        migrations.AlterField(
            model_name='comment',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 8, 7, 46, 3, 315650, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='creator',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 8, 7, 46, 3, 331276, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 8, 7, 46, 3, 315650, tzinfo=utc)),
        ),
    ]
