# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-08 08:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_auto_20170408_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 8, 8, 33, 8, 886512, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='creator',
            name='profile_image',
            field=models.ImageField(upload_to='/media'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 8, 8, 33, 8, 886512, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 8, 8, 33, 8, 886512, tzinfo=utc)),
        ),
    ]
