# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-08 09:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_auto_20170408_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 8, 9, 12, 28, 121562, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='creator',
            name='profile_image',
            field=models.ImageField(upload_to='profile'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 8, 9, 12, 28, 137187, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 8, 9, 12, 28, 121562, tzinfo=utc)),
        ),
    ]
