# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-08 09:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0018_auto_20170408_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='giveaways',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('giveaway_name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('docfile', models.FileField(upload_to='documents/%y/%m/%d')),
                ('screen_shot1', models.ImageField(upload_to='document/%y/%m/%d')),
                ('screen_shot2', models.ImageField(upload_to='document/%y/%m/%d')),
                ('screen_shot3', models.ImageField(upload_to='document/%y/%m/%d')),
                ('github_link', models.CharField(max_length=256, null=True)),
                ('website_link', models.CharField(max_length=256, null=True)),
                ('likes', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 8, 9, 17, 20, 201890, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 8, 9, 17, 20, 201890, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 8, 9, 17, 20, 186264, tzinfo=utc)),
        ),
    ]
