# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-14 11:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0022_auto_20170414_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 14, 11, 25, 58, 714593, tzinfo=utc)),
        ),
    ]
