# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-29 08:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0023_auto_20170414_1655'),
    ]

    operations = [
        migrations.DeleteModel(
            name='giveaways',
        ),
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 29, 8, 39, 32, 375776, tzinfo=utc)),
        ),
    ]
