# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-29 08:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GIVEAWAYS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('giveaway_name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('docfile', models.FileField(upload_to='documents/%y/%m/%d')),
                ('screen_shot1', models.ImageField(upload_to='document/%y/%m/%d')),
                ('screen_shot2', models.ImageField(upload_to='document/%y/%m/%d')),
                ('screen_shot3', models.ImageField(upload_to='document/%y/%m/%d')),
                ('website_link', models.CharField(max_length=256, null=True)),
                ('likes', models.IntegerField(default=0)),
            ],
        ),
    ]
