# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-29 09:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('giveaways', '0002_giveaways_github_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='giveaways',
            name='github_link',
        ),
    ]
