# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-29 14:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('giveaways', '0003_remove_giveaways_github_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Giveaway',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('giveaway_name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('file', models.FileField(upload_to='documents/%y/%m/%d')),
                ('screen_shot1', models.ImageField(upload_to='document/%y/%m/%d')),
                ('screen_shot2', models.ImageField(upload_to='document/%y/%m/%d')),
                ('screen_shot3', models.ImageField(upload_to='document/%y/%m/%d')),
                ('website_link', models.CharField(max_length=256, null=True)),
                ('likes', models.IntegerField(default=0)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='GIVEAWAYS',
        ),
    ]
